name: Main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Main Process
    runs-on: ubuntu-latest
    env:
      GOLANGCI_LINT_VERSION: v2.10.1
      YAEGI_VERSION: v0.16.1
      CGO_ENABLED: "0"

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test -v -cover ./...

      - name: Install golangci-lint ${{ env.GOLANGCI_LINT_VERSION }}
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Install Yaegi ${{ env.YAEGI_VERSION }}
        run: curl -sfL https://raw.githubusercontent.com/traefik/yaegi/master/install.sh | bash -s -- -b $(go env GOPATH)/bin ${YAEGI_VERSION}

      - name: Run Yaegi tests
        run: yaegi test -v .
